[versions]
kotlin = "2.3.10"
kotlin-coroutines = "1.10.2"
kotlin-browser = "0.5.0"
webrtc-android-sdk = "137.7151.04"
webrtc-ios-sdk = "137.7151.04"

#Android
minSdk = "21"
compileSdk = "35"
targetSdk = "35"

androidx-core = "1.16.0"
androidx-startup = "1.2.0"
androidx-test-core = "1.6.1"
androidx-test-runner = "1.6.2"
androidx-test-rules = "1.6.1"

# Plugins
agp = "8.9.3"
ktlint = "12.2.0"
vanniktech-maven-publish = "0.34.0"

[libraries]
webrtc-sdk = { module = "io.github.webrtc-sdk:android", version.ref = "webrtc-android-sdk" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin-browser" }
androidx-coreKtx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-startup = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test-rules" }

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
